// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syyqdvmzvzhiclwkuzsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5eXFkdm16dnpoaWNsd2t1enNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NjQ2MTMsImV4cCI6MjA2MTA0MDYxM30.LWI2VVmknzLyRo5xhvVBfx6rl7UW1AAxWsgdGtUG6gs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);